name: Deploy Quranqita

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Masuk ke folder project di hosting
            cd ~/domains/quranqita.pro/quranqita
            # php artisan down
            git pull origin master
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            # php artisan db:seed --class=NotificationSettingSeeder
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            # php artisan up
            echo "Deployment Berhasil!"
